projects:
  platform:
    schemaPath: amplify/backend/api/platform/build/schema.graphql
    includes:
      - libs/graphql/src/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: libs/common/src/generated-types.ts
        docsFilePath: libs/graphql/src
        region: ap-southeast-1
        apiId: null
        maxDepth: 4
extensions:
  amplify:
    version: 3
