# ===================================================================
# Configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.intelligo.systems/profiles/
# More information on configuration properties: https://www.intelligo.systems/common-application-properties/
# ===================================================================

# ===================================================================
# Standard app properties.
# ===================================================================

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${intelligo.registry.password}@localhost:8761/eureka/

server:
  port: 8090

  mail:
    host: localhost
    port: 25
    username:
    password:

# ===================================================================
# intelligo specific properties
#
# Full reference is available at: https://www.intelligo.systems/common-application-properties/
# ===================================================================

intelligo:
  mail: # specific intelligo mail property, for standard properties see MailProperties
    from: foodorder@localhost
    base-url: http://127.0.0.1:8082
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the intelligoProperties above
#
# More documentation is available at:
# https://www.intelligo.systems/common-application-properties/
# ===================================================================

# application:
