version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: elastic-search
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic
  kibana:
    image: kibana:7.16.1
    container_name: kibaba
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root
      - MARIADB_DATABASE=vendure-dev
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - '3306:3306'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
    ports:
      - 8080:80
    volumes:
      - /sessions
  redis:
    image: bitnami/redis:6.2
    hostname: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8085:8081"
  jenkins:
    image: "jenkins:2.60.3"
    container_name: "jenkins"
    restart: "always"
    ports: 
      - "9001:9001"
      - "50000:50000"
    volumes: 
      - "jenkins_home:/var/jenkins_home"

volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local
  jenkins_home:
networks:
  elastic:
    driver: bridge