name: frontend

on: [push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v2
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
      working-directory: ./frontend
    - name: Build
      run: npm run build
      working-directory: ./frontend
